### ISSUE TITLE
Pyproject.toml Inline map vs section map

### ISSUE THREAD

**Issue by Julien00859** [NotANameServer/incipyt#66]
At the moment we produce the following `pyproject.toml` for the keys license, authors and maintainers:

```toml
[[project.authors]]
name = "Julien"
email = "julien@example.com"

[[project.maintainers]]
name = "Julien"
email = "julien@example.com"

[project.license]
file = "LICENSE"
```

It would be better if we used inline-maps for those keys:

```toml
license = {file = "LICENSE"}
authors = [
  {name = "Julien", email = "julien@example.com"},
]
maintainers = [
  {name = "Julien", email = "julien@example.com"}
]
```
